window.stressCheckQuestionSets = window.stressCheckQuestionSets || {};

window.stressCheckQuestionSets.adult = {
    work: [
    "How manageable does your workload feel this week?",
    "How often do you feel stressed about finances or bills?",
    "How well have you been sleeping lately?",
    "How often do you feel mentally drained after work?",
    "How in control do you feel of your daily schedule?",
    "How often do you feel pressure to be available outside work hours?",
    "How well are you balancing work and personal life?",
    "How often do you feel tension in your body from work?",
    "How supported do you feel by colleagues or management?",
    "How satisfied are you with your current work routine?",
    "How often do you feel overwhelmed by work responsibilities?",
    "How worried are you about job stability or career progress?",
    "How easy is it for you to relax after work?",
    "How often do you feel irritable or short-tempered at work?",
    "How motivated do you feel when starting your work day?",
    "How often do you feel emotionally exhausted from work?",
    "How confident do you feel about handling work challenges?",
    "How often do you feel like you need a reset from work?",
    "How well do you feel your skills are being utilized?",
    "How often do you feel that your contributions go unrecognized?",
    "How much does office politics contribute to your daily stress?",
    "How often do you find it hard to concentrate on tasks?",
    "How much do you dread going into work on Monday morning?",
    "How often do you skip lunch or breaks to catch up on work?",
    "How safe do you feel expressing your opinions to your boss?",
    "How often do you feel that your deadlines are unrealistic?",
    "How much does the physical environment of your workplace bother you?",
    "How often do you feel that your workload is unfairly distributed?",
    "How much do you worry about making mistakes in your work?",
    "How often do you feel that meetings are a waste of your time?",
    "How much does the commute to work affect your mood?",
    "How often do you feel that you have insufficient resources to do your job?",
    "How much do you struggle to say 'no' to additional tasks?",
    "How often do you feel that your job is negatively affecting your health?",
    "How much do you worry about being replaced by technology or others?",
    "How often do you feel like you are just 'going through the motions'?",
    "How much does the fear of a performance review stress you out?",
    "How often do you feel that you lack autonomy in your role?",
    "How much do you struggle to delegate tasks to others?",
    "How often do you feel that your workplace culture is toxic?",
    "How much do you worry about the success of your company?",
    "How often do you feel that you have to choose between quality and speed?",
    "How much do you feel that your job interferes with your family time?",
    "How often do you feel that you are under-compensated for your efforts?",
    "How much does the lack of a clear job description stress you out?",
    "How often do you feel that your work is monotonous or boring?",
    "How much do you worry about communication gaps within your team?",
    "How often do you feel that you are being micro-managed?",
    "How much do you struggle with the technical requirements of your job?",
    "How often do you feel that your work has no long-term impact?"
],
  career: [
    "How uncertain do you feel about your career path?",
    "How much pressure do you feel to succeed in your career?",
    "How satisfied are you with your career progress?",
    "How often do you worry about career advancement?",
    "How confident do you feel about your career decisions?",
    "How much do you feel stuck in your current career?",
    "How often do you compare your career to others?",
    "How supported do you feel in your career development?",
    "How much do career goals stress you out?",
    "How often do you doubt your career choices?",
    "How well do you feel your career aligns with your values?",
    "How much pressure do you feel to change careers?",
    "How often do you feel behind in your career timeline?",
    "How satisfied are you with your work-life balance?",
    "How much do career uncertainty affect your personal life?",
    "How often do you feel overwhelmed by career expectations?",
    "How confident do you feel about future career opportunities?",
    "How much do you worry about your professional reputation?",
    "How often do you feel that you lack the necessary networking skills?",
    "How much do you worry about your industry becoming obsolete?",
    "How often do you feel that you need more training or education?",
    "How much does the thought of a career change frighten you?",
    "How often do you feel that you are not living up to your potential?",
    "How much do you worry about the age gap between you and your peers?",
    "How often do you feel that your current path is a 'dead end'?",
    "How much do you worry about your LinkedIn profile or resume?",
    "How often do you feel that you are 'faking it' in your profession?",
    "How much do you struggle to find a mentor in your field?",
    "How often do you feel that your career defines too much of your identity?",
    "How much do you worry about the cost of professional development?",
    "How often do you feel that you have missed out on key opportunities?",
    "How much do you worry about being overqualified for new roles?",
    "How often do you feel that your career is stagnant?",
    "How much do you struggle to balance career ambition with personal peace?",
    "How often do you feel that you are working in the wrong industry entirely?",
    "How much do you worry about the political climate affecting your career?",
    "How often do you feel that your career goals are unrealistic?",
    "How much do you worry about the impact of your career on your health?",
    "How often do you feel that you are being held back by a lack of connections?",
    "How much do you worry about your ability to adapt to new work trends?",
    "How often do you feel that your career is a source of disappointment for others?",
    "How much do you worry about the lack of diversity in your field?",
    "How often do you feel that you have to compromise your ethics for success?",
    "How much do you worry about the long-term viability of your current company?",
    "How often do you feel that your career growth has reached a ceiling?",
    "How much do you worry about the transition to a leadership role?",
    "How often do you feel that you are working for the wrong reasons (e.g., just money)?",
    "How much do you worry about the balance between passion and profit?",
    "How often do you feel that you have no 'Plan B' for your career?",
    "How much do you worry about the physical toll of your career over time?"
],
    financial: [
    "How often do you worry about financial stability?",
    "How much do you struggle with bills and expenses?",
    "How stressed do you feel about debt or loans?",
    "How often do financial concerns affect your sleep?",
    "How confident do you feel about your financial future?",
    "How much pressure do you feel to save money?",
    "How often do you worry about emergency expenses?",
    "How well do you feel you're managing your budget?",
    "How much do financial stress affect your relationships?",
    "How often do you feel unable to afford things you need?",
    "How worried are you about retirement savings?",
    "How much does financial uncertainty affect your health?",
    "How often do you argue with partner about money?",
    "How satisfied are you with your current income?",
    "How much do financial goals stress you out?",
    "How often do you feel behind financially compared to peers?",
    "How well do you feel prepared for financial emergencies?",
    "How much does cost of living impact your stress?",
    "How often do you feel guilty about spending?",
    "How much do you worry about your credit score?",
    "How often do you feel that you are living paycheck to paycheck?",
    "How much does the thought of taxes stress you out?",
    "How often do you feel that you cannot afford to take a vacation?",
    "How much do you worry about the cost of healthcare?",
    "How often do you feel that you are not earning what you are worth?",
    "How much do you worry about your children's financial future?",
    "How often do you feel that you have too many subscription costs?",
    "How much does inflation change your daily spending habits?",
    "How often do you feel that you are unable to help family members financially?",
    "How much do you worry about the fluctuating housing market?",
    "How often do you feel that you lack a clear investment strategy?",
    "How much do you worry about the cost of home or car repairs?",
    "How often do you feel that you are drowning in interest payments?",
    "How much do you worry about losing your primary source of income?",
    "How often do you feel that you can't afford to eat healthily?",
    "How much do you worry about identity theft or financial fraud?",
    "How often do you feel that you are not saving enough for a 'rainy day'?",
    "How much do you worry about the cost of insurance premiums?",
    "How often do you feel that your lifestyle is becoming too expensive?",
    "How much do you worry about the stock market or your investments?",
    "How often do you feel that you have no one to go to for financial advice?",
    "How much do you worry about the cost of supporting aging parents?",
    "How often do you feel that you are forced to work overtime for money?",
    "How much do you worry about the debt-to-income ratio of your household?",
    "How often do you feel that you are sacrificing your happiness for a salary?",
    "How much do you worry about being able to afford a major life event (e.g., wedding)?",
    "How often do you feel that financial planning is too complicated?",
    "How much do you worry about the impact of student loans on your life?",
    "How often do you feel that you have to hide your financial struggles from others?",
    "How much do you worry about being able to pay off your mortgage one day?"
],
    relationships: [
    "How often do relationship issues stress you out?",
    "How much do you feel emotionally drained by others?",
    "How well do you communicate in your relationships?",
    "How often do you feel misunderstood by your partner?",
    "How much do relationship conflicts affect your work?",
    "How supported do you feel in your relationships?",
    "How often do you worry about relationship stability?",
    "How much do relationship expectations stress you out?",
    "How well do you balance relationships with other life areas?",
    "How often do you feel lonely in your relationships?",
    "How much do relationship problems affect your sleep?",
    "How confident do you feel about resolving conflicts?",
    "How often do you feel pressure to please others?",
    "How well do you set boundaries in relationships?",
    "How much do relationship stress affect your health?",
    "How often do you doubt your relationship decisions?",
    "How satisfied are you with your social support system?",
    "How much do relationship issues affect your concentration?",
    "How often do you feel overwhelmed by relationship responsibilities?",
    "How well do you handle relationship disagreements?",
    "How much do relationship uncertainty affect your mood?",
    "How often do you feel that you are the only one making an effort?",
    "How much do you worry about being judged by your partner's family?",
    "How often do you feel that you lack 'me time' because of others?",
    "How much do you worry about losing a close friendship?",
    "How often do you feel that your partner is not listening to you?",
    "How much do you struggle to trust people in your life?",
    "How often do you feel that you have to 'walk on eggshells' around someone?",
    "How much do you worry about the long-term future of your current relationship?",
    "How often do you feel that your social circle is shrinking?",
    "How much do you worry about being a 'good' partner or friend?",
    "How often do you feel that you are being taken advantage of by others?",
    "How much do you worry about the lack of intimacy in your relationship?",
    "How often do you feel that your friends are too busy for you?",
    "How much do you struggle to share your true self with others?",
    "How often do you feel that your relationship values have changed?",
    "How much do you worry about the impact of your stress on your partner?",
    "How often do you feel that your social life is a source of obligation?",
    "How much do you struggle with feelings of jealousy or envy?",
    "How often do you feel that you are neglected by those you care about?",
    "How much do you worry about the frequency of your arguments?",
    "How often do you feel that you and your partner are 'drifting apart'?",
    "How much do you struggle to forgive someone after a mistake?",
    "How often do you feel that you have to hide your problems from your friends?",
    "How much do you worry about being alone in the future?",
    "How often do you feel that your partner's habits are unbearable?",
    "How much do you struggle to meet new people and make friends?",
    "How often do you feel that your family interferes with your relationship?",
    "How much do you worry about the secrets you keep from those close to you?",
    "How often do you feel that your relationships are the biggest source of your stress?"
]
};