
window.stressCheckQuestionSets = window.stressCheckQuestionSets || {};

window.stressCheckQuestionSets.adult = [
    "How manageable does your workload feel this week?",
    "How often do you feel stressed about finances or bills?",
    "How well have you been sleeping lately?",
    "How often do you feel mentally drained after work?",
    "How in control do you feel of your daily schedule?",
    "How often do you feel pressure to be available (messages/calls) outside work hours?",
    "How well are you balancing work and personal life right now?",
    "How often do you feel tension in your body (neck, shoulders, headaches)?",
    "How supported do you feel by the people around you?",
    "How satisfied are you with your current routine?",
    "How often do you feel overwhelmed by responsibilities at home?",
    "How often do you worry about job stability or career progress?",
    "How easy is it for you to relax when you have free time?",
    "How often do you feel irritable or short-tempered lately?",
    "How healthy have your eating habits been recently?",
    "How often do you skip breaks because you feel behind?",
    "How motivated do you feel when starting your day?",
    "How often do you feel emotionally exhausted?",
    "How confident do you feel about handling current challenges?",
    "How often do you feel like you need a reset or time off?",
    "How much do you feel your skills are being utilized at work?",
    "How often do you experience 'imposter syndrome' or self-doubt?",
    "How satisfied are you with the communication from your management?",
    "How often do you find yourself thinking about work during dinner?",
    "How much does your office or workspace environment affect your focus?",
    "How often do you feel you have to compete with colleagues?",
    "How much control do you have over your career path right now?",
    "How often do you feel unappreciated for the extra effort you put in?",
    "How satisfied are you with your professional networking or connections?",
    "How often do you feel stuck in a 'dead-end' task or project?",
    "How often do you experience a lack of energy by mid-afternoon?",
    "How frequently do you use caffeine or energy drinks to stay alert?",
    "How often do you experience digestive issues when you are busy?",
    "How satisfied are you with your current level of physical fitness?",
    "How often do you ignore physical pain to keep working?",
    "How much does your posture during the day cause you discomfort?",
    "How often do you feel that your vision is strained from screen time?",
    "How well do you feel you are aging physically?",
    "How often do you prioritize others' health over your own?",
    "How much does the quality of your air/light at home affect your mood?",
    "How often do you worry about your retirement or long-term savings?",
    "How confident do you feel about your ability to handle an emergency expense?",
    "How much does the cost of living in your area impact your stress?",
    "How often do you feel guilty about spending money on yourself?",
    "How satisfied are you with your current insurance or benefits?",
    "How much does debt (loans/credit cards) weigh on your mind?",
    "How often do you feel pressure to keep up with the spending of peers?",
    "How secure do you feel in your current housing situation?",
    "How much do you worry about the economic future of your country?",
    "How often do you feel that your income is not proportional to your effort?",
    "How often do you feel lonely despite having social connections?",
    "How much do you feel your partner or family understands your stress?",
    "How often do you feel like you are 'carrying' the emotions of others?",
    "How satisfied are you with the quality of your friendships?",
    "How often do you feel forced to attend social events when tired?",
    "How much do you worry about the health of your aging parents?",
    "How often do you feel judged by your extended family?",
    "How satisfied are you with your ability to resolve conflicts?",
    "How often do you feel you have to hide your struggles from friends?",
    "How much do you feel your social circle encourages a healthy lifestyle?",
    "How often do you feel that your life lacks a clear sense of purpose?",
    "How much do you worry about the legacy you are leaving behind?",
    "How often do you feel that you have 'settled' in life?",
    "How frequently do you feel a sense of nostalgia for the past?",
    "How much do you trust your intuition when making big decisions?",
    "How often do you feel overwhelmed by the state of the world news?",
    "How much do you struggle with perfectionism in your daily tasks?",
    "How often do you feel that time is moving too quickly?",
    "How satisfied are you with your personal growth over the last year?",
    "How often do you feel that you are living for someone else's goals?",
    "How often do you feel that your home is too cluttered or disorganized?",
    "How much do you enjoy the neighborhood you live in?",
    "How often do you feel that you lack a creative outlet?",
    "How satisfied are you with the amount of time you spend outdoors?",
    "How often do you feel like your technology (phone/PC) is controlling you?",
    "How much do you worry about your digital privacy?",
    "How often do you feel that you don't have enough time for a hobby?",
    "How frequently do you feel that your commute is a waste of life?",
    "How satisfied are you with your sleep environment (bed/room)?",
    "How often do you feel that your diet is driven by stress?",
    "How often do you struggle to make even simple decisions?",
    "How frequently do you find yourself ruminating on past mistakes?",
    "How much do you feel that your mind is 'noisy' or crowded?",
    "How often do you feel a sense of panic when your schedule changes?",
    "How well do you think you handle unexpected criticism?",
    "How often do you feel that your emotions are 'numb' or flat?",
    "How much do you find it difficult to start a new, large task?",
    "How often do you feel that you have lost your sense of wonder?",
    "How satisfied are you with your mental resilience?",
    "How often do you feel that you are on the verge of a breakdown?",
    "How much do you feel you can truly be yourself at work?",
    "How often do you feel that you are missing out on life?",
    "How much do you believe that things will get better next month?",
    "How often do you take deep breaths to calm yourself down?",
    "How satisfied are you with your life overall?",
    "How much do you feel you have a 'safe space' to go to?",
    "How often do you feel that you have reached your potential?",
    "How frequently do you feel grateful for the small things?",
    "How would you rate your ability to cope with today's stress?",
    "How would you rate your overall stress level right now?"
];
