
window.stressCheckQuestionSets = window.stressCheckQuestionSets || {};

window.stressCheckQuestionSets.general = [
    "How would you rate your overall energy level today?",
    "How often do you feel like you have enough time for yourself?",
    "How well have you been sleeping lately?",
    "How often do you feel overwhelmed by the news or social media?",
    "How satisfied are you with your physical health right now?",
    "How often do you feel a sense of calm in your daily life?",
    "How much do you feel in control of your future?",
    "How often do you find yourself overthinking small decisions?",
    "How supported do you feel by your friends and family?",
    "How often do you feel tension in your body, like your neck or shoulders?",
    "How satisfied are you with your current living environment?",
    "How often do you feel like you are rushing to get things done?",
    "How much do you enjoy your daily routine?",
    "How often do you feel irritable without a clear reason?",
    "How easy is it for you to focus on a single task?",
    "How often do you feel that your efforts are ignored by others?",
    "How satisfied are you with your work-life balance (or study-life)?",
    "How often do you feel physically exhausted by the end of the day?",
    "How much do you worry about things that haven't happened yet?",
    "How often do you feel a sense of accomplishment?",
    "How often do you spend time outdoors or in nature?",
    "How satisfied are you with your eating habits lately?",
    "How often do you feel that your digital devices are a distraction?",
    "How much do you feel that your hobbies help you relax?",
    "How often do you feel like you are 'on autopilot'?",
    "How satisfied are you with your level of physical activity?",
    "How often do you skip breaks during the day?",
    "How much do you feel that clutter in your home affects your mood?",
    "How often do you feel that you have to please others before yourself?",
    "How satisfied are you with your current sleep schedule?",
    "How often do you feel lonely even when people are around?",
    "How much do you feel understood by those closest to you?",
    "How often do you find it hard to express your feelings?",
    "How satisfied are you with your social life right now?",
    "How often do you compare your life to others' lives?",
    "How much do you trust your own judgment during a crisis?",
    "How often do you feel guilty for doing nothing?",
    "How satisfied are you with your ability to handle unexpected changes?",
    "How often do you feel defensive during a conversation?",
    "How much do you value your own opinion over others' criticism?",
    "How often do you feel like your mind is 'too busy'?",
    "How frequently do you forget small tasks or appointments?",
    "How much do you struggle to start something you need to do?",
    "How often do you feel that there is too much noise in your environment?",
    "How satisfied are you with your memory lately?",
    "How often do you find yourself dwelling on past mistakes?",
    "How much do you feel that you are losing your sense of humor?",
    "How often do you feel a lack of motivation to do things you enjoy?",
    "How satisfied are you with your ability to learn new things?",
    "How often do you feel like you are carrying a heavy mental load?",
    "How often do you feel optimistic about the coming month?",
    "How much do you feel that your life has a clear direction?",
    "How often do you feel that you are making a difference?",
    "How satisfied are you with your personal growth this year?",
    "How often do you feel that you have reached a plateau?",
    "How much do you worry about things you cannot change?",
    "How often do you feel a sense of gratitude?",
    "How satisfied are you with your ability to stay present (mindfulness)?",
    "How often do you feel like you are living life to the fullest?",
    "How much do you trust that things will work out in the end?",
    "How often do you experience headaches or eye strain?",
    "How frequently do you feel restless or unable to sit still?",
    "How often do you feel that your heart rate increases due to stress?",
    "How much do you notice your breathing during the day?",
    "How often do you feel that your body needs more rest than it gets?",
    "How satisfied are you with your current energy levels in the morning?",
    "How often do you feel a 'tightness' in your chest?",
    "How much do you feel that your physical surroundings are safe?",
    "How often do you experience sudden changes in your appetite?",
    "How well do you feel you recover from a cold or minor illness?",
    "How often do you feel stressed by your commute or travel?",
    "How much do you worry about your financial security?",
    "How often do you feel that your chores are never-ending?",
    "How satisfied are you with your access to fresh air and light?",
    "How often do you feel that you have too many responsibilities?",
    "How much do you feel pressured by the expectations of society?",
    "How often do you feel that you are being judged by strangers?",
    "How satisfied are you with your ability to disconnect from work/tasks?",
    "How often do you feel that you are losing your patience?",
    "How much do you feel that your daily life is meaningful?",
    "How often do you use deep breathing to calm down?",
    "How much do you feel you can handle a sudden emergency?",
    "How often do you reach out for help when you are struggling?",
    "How satisfied are you with your ability to bounce back from a bad day?",
    "How often do you find beauty in small things?",
    "How much do you feel that you can change your own mood?",
    "How often do you feel that you have a 'safe place' to go to?",
    "How satisfied are you with your boundaries (saying 'no')?",
    "How often do you feel that you are learning from your failures?",
    "How much do you feel that you are in charge of your own happiness?",
    "How often do you feel that you are at peace with yourself?",
    "How satisfied are you with the person you are becoming?",
    "How often do you feel that you have enough fun in your life?",
    "How much do you feel that your voice matters?",
    "How often do you feel that you are being true to yourself?",
    "How satisfied are you with your ability to forgive yourself?",
    "How often do you feel that today was a productive day?",
    "How much do you believe in your own potential?",
    "How would you rate your ability to cope with stress right now?",
    "Overall, how happy have you felt in the last 24 hours?"
];
