window.stressCheckQuestionSets = window.stressCheckQuestionSets || {};

window.stressCheckQuestionSets.general = {
    emotional: [
        "How would you rate your overall energy level today?",
        "How often do you feel emotionally drained?",
        "How well have you been sleeping lately?",
        "How often do you feel overwhelmed by your emotions?",
        "How satisfied are you with your emotional health?",
        "How often do you feel a sense of calm in your daily life?",
        "How much do you feel in control of your feelings?",
        "How often do you find yourself overthinking emotional situations?",
        "How supported do you feel emotionally by friends and family?",
        "How often do you feel tension in your body from stress?",
        "How satisfied are you with how you handle emotions?",
        "How often do you feel like you're rushing emotionally?",
        "How much do you enjoy your emotional state?",
        "How often do you feel irritable without emotional reason?",
        "How easy is it for you to focus on emotional tasks?",
        "How often do you feel your emotions are ignored by others?",
        "How satisfied are you with your emotional balance?",
        "How often do you feel physically exhausted from emotions?",
        "How much do you worry about emotional situations?",
        "How often do you feel emotional accomplishment?"
    ],
    mental: [
        "How often do you feel like you have enough mental time for yourself?",
        "How often do you feel overwhelmed by news or social media?",
        "How satisfied are you with your mental clarity?",
        "How often do you feel a sense of mental calm?",
        "How much do you feel in control of your thoughts?",
        "How often do you find yourself overthinking small decisions?",
        "How supported do you feel mentally by friends and family?",
        "How often do you feel mental tension in your body?",
        "How satisfied are you with your current mental environment?",
        "How often do you feel like you're rushing mentally?",
        "How much do you enjoy your mental state?",
        "How often do you feel mentally irritable?",
        "How easy is it for you to focus on mental tasks?",
        "How often do you feel your mental efforts are ignored?",
        "How satisfied are you with your mental work-life balance?",
        "How often do you feel mentally exhausted by end of day?",
        "How much do you worry about mental things that haven't happened?",
        "How often do you feel a sense of mental accomplishment?",
        "How often do you spend time in nature for mental clarity?",
        "How satisfied are you with your eating habits for mental health?",
        "How often do you feel digital devices affect your mental state?",
        "How much do your hobbies help you mentally relax?",
        "How often do you feel like you're on mental autopilot?",
        "How satisfied are you with your mental physical activity?",
        "How often do you skip mental breaks during the day?",
        "How much does clutter affect your mental mood?",
        "How often do you feel you have to please others mentally?",
        "How satisfied are you with your mental sleep schedule?",
        "How often do you feel mentally lonely?",
        "How much do you feel understood mentally by others?",
        "How often do you find it hard to express mental feelings?",
        "How satisfied are you with your mental social life?",
        "How often do you compare your mental life to others?",
        "How much do you trust your mental judgment?",
        "How often do you feel guilty for doing nothing mentally?",
        "How satisfied are you with your ability to handle mental changes?",
        "How often do you feel mentally defensive?",
        "How much do you value your mental opinion?",
        "How often do you feel your mind is too busy?",
        "How often do you forget mental tasks?",
        "How much do you struggle to start mental tasks?",
        "How satisfied are you with your mental memory?",
        "How often do you dwell on past mental mistakes?",
        "How satisfied are you with your mental motivation?",
        "How often do you feel like you're carrying mental load?",
        "How often do you feel mentally optimistic?",
        "How much do you feel your life has mental direction?",
        "How often do you feel you're making mental difference?",
        "How satisfied are you with your mental personal growth?",
        "How often do you feel you've reached mental plateau?",
        "How much do you worry about mental things you can't change?",
        "How often do you feel mental gratitude?",
        "How satisfied are you with your mental mindfulness?",
        "How often do you feel you're living mentally to fullest?",
        "How much do you trust things will work out mentally?",
        "How often do you experience mental headaches?",
        "How often do you feel mentally restless?",
        "How often do you feel your heart rate increases mentally?",
        "How much do you notice your mental breathing?",
        "How often does your body need mental rest?",
        "How satisfied are you with your morning mental energy?",
        "How often do you feel mental tightness?",
        "How much do you feel your surroundings are mentally safe?",
        "How often do you experience mental appetite changes?",
        "How well do you recover mentally from illness?",
        "How often do you feel stressed by mental commute?",
        "How much do you worry about mental security?",
        "How often do you feel your chores are mentally endless?",
        "How satisfied are you with your access to mental fresh air?",
        "How often do you feel you have too many mental responsibilities?",
        "How much do you feel pressured by mental society?",
        "How often do you feel judged mentally by strangers?",
        "How satisfied are you with your ability to disconnect mentally?",
        "How often do you feel you're losing mental patience?",
        "How much do you feel your daily life is mentally meaningful?",
        "How often do you use deep breathing for mental calm?",
        "How much do you feel you can handle mental emergencies?",
        "How often do you reach out for mental help?",
        "How satisfied are you with your ability to bounce back mentally?",
        "How often do you find mental beauty in small things?",
        "How much do you feel you can change your mental mood?",
        "How often do you feel you have a mental safe place?",
        "How satisfied are you with your mental boundaries?",
        "How often do you feel you're learning from mental failures?",
        "How much do you feel you're in charge of mental happiness?",
        "How often do you feel at mental peace with yourself?",
        "How satisfied are you with the person you're becoming mentally?",
        "How often do you feel you have enough mental fun?",
        "How much do you feel your mental voice matters?",
        "How often do you feel you're being mentally true to yourself?",
        "How satisfied are you with your ability to forgive mentally?",
        "How often do you feel today was mentally productive?",
        "How much do you believe in your mental potential?",
        "How would you rate your ability to cope with mental stress?",
        "How happy have you felt in the last 24 hours mentally?"
    ],
    life: [
        "How would you rate your overall life satisfaction?",
        "How often do you feel overwhelmed by life responsibilities?",
        "How well are you managing your life balance?",
        "How often do you feel stuck in your current life situation?",
        "How satisfied are you with your life direction?",
        "How much do you feel in control of your life path?",
        "How often do you worry about life decisions?",
        "How supported do you feel in your life journey?",
        "How often do you feel tension about life matters?",
        "How satisfied are you with your current life routine?",
        "How often do you feel like you're rushing through life?",
        "How much do you enjoy your current life?",
        "How often do you feel irritable about life in general?",
        "How easy is it for you to focus on life goals?",
        "How often do you feel your life efforts are ignored?",
        "How satisfied are you with your life balance?",
        "How often do you feel exhausted by life demands?",
        "How much do you worry about life uncertainties?",
        "How often do you feel a sense of life accomplishment?",
        "How often do you spend time outdoors for life clarity?",
        "How satisfied are you with your life habits?",
        "How often do you feel life devices are a distraction?",
        "How much do your life hobbies help you relax?",
        "How often do you feel like you're on life autopilot?",
        "How satisfied are you with your life physical activity?",
        "How often do you skip life breaks during the day?",
        "How much does life clutter affect your mood?",
        "How often do you feel you have to please others in life?",
        "How satisfied are you with your life sleep schedule?",
        "How often do you feel lonely in your life?",
        "How much do you feel understood in your life?",
        "How often do you find it hard to express life feelings?",
        "How satisfied are you with your life social connections?",
        "How often do you compare your life to others?",
        "How much do you trust your life judgment?",
        "How often do you feel guilty about life choices?",
        "How satisfied are you with your ability to handle life changes?",
        "How often do you feel defensive about life matters?",
        "How much do you value your life opinion?",
        "How often do you feel your mind is too busy with life?",
        "How often do you forget life tasks?",
        "How much do you struggle to start life tasks?",
        "How satisfied are you with your life memory?",
        "How often do you dwell on past life mistakes?",
        "How satisfied are you with your life motivation?",
        "How often do you feel like you're carrying life load?",
        "How often do you feel optimistic about life?",
        "How much do you feel your life has direction?",
        "How often do you feel you're making life difference?",
        "How satisfied are you with your life personal growth?",
        "How often do you feel you've reached life plateau?",
        "How much do you worry about life things you can't change?",
        "How often do you feel life gratitude?",
        "How satisfied are you with your life mindfulness?",
        "How often do you feel you're living life to fullest?",
        "How much do you trust life will work out?",
        "How often do you experience life headaches?",
        "How often do you feel life restless?",
        "How often do you feel your heart rate increases with life?",
        "How much do you notice your life breathing?",
        "How often does your body need life rest?",
        "How satisfied are you with your morning life energy?",
        "How often do you feel life tightness?",
        "How much do you feel your surroundings are life safe?",
        "How often do you experience life appetite changes?",
        "How well do you recover from life illnesses?",
        "How often do you feel stressed by life commute?",
        "How much do you worry about life security?",
        "How often do you feel your life chores are endless?",
        "How satisfied are you with your access to life fresh air?",
        "How often do you feel you have too many life responsibilities?",
        "How much do you feel pressured by life society?",
        "How often do you feel judged by life strangers?",
        "How satisfied are you with your ability to disconnect from life?",
        "How often do you feel you're losing life patience?",
        "How much do you feel your daily life is meaningful?",
        "How often do you use deep breathing for life calm?",
        "How much do you feel you can handle life emergencies?",
        "How often do you reach out for life help?",
        "How satisfied are you with your ability to bounce back from life?",
        "How often do you find life beauty in small things?",
        "How much do you feel you can change your life mood?",
        "How often do you feel you have a life safe place?",
        "How satisfied are you with your life boundaries?",
        "How often do you feel you're learning from life failures?",
        "How much do you feel you're in charge of life happiness?",
        "How often do you feel at life peace with yourself?",
        "How satisfied are you with the person you're becoming in life?",
        "How often do you feel you have enough life fun?",
        "How much do you feel your life voice matters?",
        "How often do you feel you're being true to yourself in life?",
        "How satisfied are you with your ability to forgive yourself in life?",
        "How often do you feel today was life productive?",
        "How much do you believe in your life potential?",
        "How would you rate your ability to cope with life stress?",
        "How happy have you felt in the last 24 hours in life?"
    ]
};