
window.stressCheckQuestionSets = window.stressCheckQuestionSets || {};

window.stressCheckQuestionSets.student = [
    "How overwhelmed do you feel by your current school assignments?",
    "How often do you worry about your grades or GPA?",
    "How well are you sleeping on school nights?",
    "How much pressure do you feel to fit in with your peers?",
    "How often do you feel anxious before a test or presentation?",
    "How supported do you feel by your teachers or mentors?",
    "How often do you feel you have too much homework to enjoy your hobbies?",
    "How comfortable do you feel participating in class discussions?",
    "How often do you feel drained after a full day of school?",
    "How confident do you feel about your plans after graduation?",
    "How much do you worry about disappointing your parents with your performance?",
    "How often do you feel left out of social groups or events?",
    "How balanced is your time between studying and seeing friends?",
    "How often do you feel restless or bored during lessons?",
    "How much does social media make you feel like you're missing out?",
    "How often do you skip meals because you are busy or stressed?",
    "How safe and comfortable do you feel while at school?",
    "How often do you feel like you are being compared to other students?",
    "How much do you worry about your physical appearance?",
    "How often do you feel like you need a break from academic expectations?",
    "How often do you feel you have to stay up late to finish projects?",
    "How much does the thought of college or future careers stress you out?",
    "How often do you feel that your parents expect too much from you?",
    "How comfortable do you feel asking for help when you don't understand a topic?",
    "How often do you feel distracted by your phone while trying to study?",
    "How much do you worry about 'fitting in' with the popular groups?",
    "How often do you feel that you have no one to talk to about your problems?",
    "How satisfied are you with your extracurricular activities?",
    "How often do you feel nervous about speaking up in front of others?",
    "How much does cyberbullying or online drama affect your mood?",
    "How often do you feel like you are falling behind your classmates?",
    "How frequently do you experience 'brain fog' during long study sessions?",
    "How much do you feel defined by your test scores?",
    "How often do you feel that your teachers don't understand your struggles?",
    "How satisfied are you with the amount of free time you have on weekends?",
    "How often do you feel jealous of your friends' achievements?",
    "How much do you worry about your family's financial situation?",
    "How often do you feel physical symptoms like a stomach ache before school?",
    "How frequently do you feel like quitting a club or a sport you used to love?",
    "How much do you feel that your identity is shaped by your grades?",
    "How often do you feel lonely in the school hallways?",
    "How satisfied are you with your morning routine before school?",
    "How often do you feel that school rules are too restrictive?",
    "How much do you worry about being judged for your clothes or style?",
    "How often do you feel that you are being ignored by your friends?",
    "How frequently do you feel like you are 'burning out'?",
    "How much do you enjoy the subjects you are currently taking?",
    "How often do you feel that you have to act a certain way to be liked?",
    "How satisfied are you with your ability to stay organized?",
    "How often do you feel that your hobbies are a waste of time?",
    "How much do you worry about your safety online?",
    "How often do you feel that your teachers are unfair?",
    "How frequently do you have trouble waking up in the morning?",
    "How much do you value your own opinions over what others think?",
    "How often do you feel that you are the only one struggling?",
    "How satisfied are you with your relationship with your siblings?",
    "How often do you feel that your workspace at home is too distracting?",
    "How much do you worry about making mistakes in front of others?",
    "How often do you feel that you are being pushed into a career you don't want?",
    "How frequently do you feel frustrated by slow internet or tech issues?",
    "How much do you feel that your lunch breaks are long enough to recharge?",
    "How often do you feel that your classmates are overly competitive?",
    "How satisfied are you with your ability to handle criticism?",
    "How often do you feel that you are living in someone else's shadow?",
    "How much do you worry about the environment or the state of the world?",
    "How often do you feel that you have to hide your true interests?",
    "How frequently do you feel like you are wasting your potential?",
    "How much do you trust your friends with your secrets?",
    "How often do you feel that your weekend is spent entirely on chores or work?",
    "How satisfied are you with your school's support for mental health?",
    "How often do you feel that you are being teased or picked on?",
    "How much do you worry about being 'canceled' or judged online?",
    "How often do you feel that your life is too controlled by adults?",
    "How frequently do you feel a lack of energy to do things you enjoy?",
    "How much do you feel that your school spirit or sense of belonging is high?",
    "How often do you feel that you are failing at being a 'good' student?",
    "How satisfied are you with your ability to make new friends?",
    "How often do you feel that you have to choose between sleep and grades?",
    "How much do you worry about your privacy being invaded?",
    "How often do you feel that your efforts aren't being noticed?",
    "How frequently do you feel overwhelmed by the noise in school?",
    "How much do you feel that you can be yourself around your family?",
    "How often do you feel that your future is out of your hands?",
    "How satisfied are you with your ability to manage your anger?",
    "How often do you feel that you are losing your creativity?",
    "How much do you worry about your performance in gym or physical education?",
    "How often do you feel that you are working harder than everyone else?",
    "How frequently do you feel like you are on an emotional rollercoaster?",
    "How much do you feel that you have a clear purpose right now?",
    "How often do you feel that your house is too loud for studying?",
    "How satisfied are you with your ability to ignore rumors?",
    "How often do you feel that you are expected to be perfect?",
    "How much do you worry about not being 'smart' enough?",
    "How often do you feel that you are drifting away from your childhood friends?",
    "How frequently do you feel like your thoughts are racing?",
    "How much do you feel that your teachers actually enjoy teaching?",
    "How often do you feel that your contributions to a group project are ignored?",
    "How satisfied are you with your ability to relax without feeling guilty?",
    "How often do you feel that today was a successful day?",
    "How would you rate your overall level of stress today?"
];
