window.stressCheckQuestionSets = window.stressCheckQuestionSets || {};

window.stressCheckQuestionSets.student = {
    education: [
    "How overwhelmed do you feel by your current school assignments?",
    "How often do you worry about your grades or GPA?",
    "How well are you sleeping on school nights?",
    "How supported do you feel by your teachers or mentors?",
    "How often do you feel you have too much homework to enjoy your hobbies?",
    "How comfortable do you feel participating in class discussions?",
    "How often do you feel drained after a full day of school?",
    "How confident do you feel about your plans after graduation?",
    "How much do you worry about disappointing your parents with your performance?",
    "How often do you feel like you need a break from academic expectations?",
    "How much does the thought of upcoming exams disrupt your focus?",
    "How often do you procrastinate on major projects?",
    "How difficult is it for you to concentrate during lectures?",
    "How often do you feel that your curriculum is too difficult?",
    "How much do you struggle with time management?",
    "How often do you feel like you are falling behind your classmates?",
    "How much anxiety do you feel when receiving feedback on assignments?",
    "How often do you feel that your efforts are not reflected in your grades?",
    "How many times a week do you stay up past midnight to study?",
    "How much do you worry about college entrance exams (SAT/ACT/etc.)?",
    "How often do you feel physically ill because of school stress?",
    "How satisfied are you with your choice of subjects or major?",
    "How often do you feel that teachers' instructions are unclear?",
    "How much pressure do you feel to take advanced or honors classes?",
    "How often do you feel like 'imposter syndrome'—that you aren't as smart as others think?",
    "How much do you struggle to balance extracurriculars with schoolwork?",
    "How often do you feel that the grading system is unfair?",
    "How much does a single bad grade ruin your entire week?",
    "How often do you feel that your school environment is overly competitive?",
    "How much do you struggle to find a quiet place to study?",
    "How often do you feel that you lack the resources needed to succeed?",
    "How much do you worry about your class ranking?",
    "How often do you feel that your education is irrelevant to your future goals?",
    "How much do you struggle to keep your study materials organized?",
    "How often do you feel pressure to be 'perfect' in every subject?",
    "How much do you worry about your attendance record?",
    "How often do you feel that you have no voice in your school’s policies?",
    "How much does the length of the school day affect your mental health?",
    "How often do you feel that you are just memorizing things rather than learning?",
    "How much do you struggle to ask for help when you don’t understand a concept?",
    "How often do you feel that your school counselor is inaccessible?",
    "How much do you worry about the transition to the next grade level?",
    "How often do you feel that the workload is physically impossible to complete?",
    "How much do you struggle with online learning platforms?",
    "How often do you feel that your creative talents are ignored by school?",
    "How much does the fear of failure prevent you from trying new subjects?",
    "How often do you feel that your teachers have unrealistic expectations?",
    "How much do you worry about your writing or presentation skills?",
    "How often do you feel that your school lack adequate mental health support?",
    "How much do you feel that your worth is tied solely to your academic success?"
],
    social: [
    "How much pressure do you feel to fit in with your peers?",
    "How often do you feel anxious before a test or presentation?",
    "How often do you feel left out of social groups or events?",
    "How balanced is your time between studying and seeing friends?",
    "How often do you feel restless or bored during lessons?",
    "How much does social media make you feel like you're missing out?",
    "How safe and comfortable do you feel while at school?",
    "How often do you feel like you are being compared to other students?",
    "How much do you worry about your physical appearance?",
    "How often do you feel lonely even when surrounded by people?",
    "How much do you worry about being judged for your clothes or style?",
    "How often do you feel pressured to act differently to please friends?",
    "How much does gossip or rumors at school affect your peace of mind?",
    "How often do you feel you have to 'mask' your true personality?",
    "How much do you worry about your reputation among your peers?",
    "How often do you feel that your friends don’t truly understand you?",
    "How much anxiety do you feel when meeting new people?",
    "How often do you feel pressured to participate in activities you don't like?",
    "How much does conflict with a friend distract you from your work?",
    "How often do you feel that social media consumes too much of your time?",
    "How much do you worry about being 'canceled' or excluded online?",
    "How often do you feel that you are the only one struggling socially?",
    "How much do you worry about finding a partner or dating?",
    "How often do you feel that you have to compete for your friends' attention?",
    "How much do you feel that you have to be 'online' 24/7 to stay relevant?",
    "How often do you feel that your social life is more stressful than school?",
    "How much do you struggle to set boundaries with your friends?",
    "How often do you feel that your peers are more successful than you?",
    "How much do you worry about being bullied or teased?",
    "How often do you feel that you don't have a 'best' friend to talk to?",
    "How much do you worry about how many likes or comments you get?",
    "How often do you feel that people only like you for what you can do for them?",
    "How much do you struggle to maintain long-distance friendships?",
    "How often do you feel that you are too shy to make the first move?",
    "How much do you worry about being invited to parties or gatherings?",
    "How often do you feel that your social group is toxic or draining?",
    "How much do you worry about your social status at school?",
    "How often do you feel that you are 'drifting away' from your childhood friends?",
    "How much do you worry about saying the 'wrong thing' in a group?",
    "How often do you feel that you have to buy things just to keep up with trends?",
    "How much do you worry about your tone of voice in text messages?",
    "How often do you feel that you are ignored in group chats?",
    "How much do you struggle with eye contact during conversations?",
    "How often do you feel that you are the 'backup' friend?",
    "How much do you worry about your friends' opinions of your family?",
    "How often do you feel that you can't be yourself on social media?",
    "How much do you struggle to apologize after a social misunderstanding?",
    "How often do you feel that people are talking behind your back?",
    "How much do you worry about being boring to others?",
    "How often do you feel that you have no one to sit with at lunch?"
],
   financial: [
    "How often do you skip meals because you are busy or stressed?",
    "How much do you worry about your daily expenses?",
    "How do you struggle to manage your allowance?",
    "How often do you feel pressure to buy things you can't afford?",
    "How much does your family's financial situation affect your stress?",
    "How often do you worry about paying for school activities?",
    "How stressed do you feel about future college costs?",
    "How often do you feel unable to afford things your friends have?",
    "How much do financial worries affect your sleep?",
    "How often do you feel guilty about spending money?",
    "How much do you worry about the cost of textbooks and supplies?",
    "How often do you turn down social invitations because they cost too much?",
    "How much do you worry about your parents' job security?",
    "How often do you think about getting a part-time job to help out?",
    "How much does the cost of transportation to school bother you?",
    "How often do you feel stressed when checking your bank account balance?",
    "How much do you worry about debt or student loans in the future?",
    "How often do you feel that you are a financial burden to your family?",
    "How much do you worry about the cost of your hobbies?",
    "How often do you compare your family’s wealth to others?",
    "How much do you worry about the rising price of food and gas?",
    "How often do you feel like you have to hide your financial status from friends?",
    "How much do you worry about being able to afford a graduation outfit?",
    "How often do you feel that you can't afford to take a day off for self-care?",
    "How much do you worry about emergency expenses (e.g., phone repair)?",
    "How often do you feel that your school expects you to spend too much money?",
    "How much do you worry about the cost of clothing for different seasons?",
    "How often do you feel that you lack the financial literacy to manage money?",
    "How much do you worry about inflation affecting your future lifestyle?",
    "How often do you feel pressured to tip more than you can afford?",
    "How much do you worry about the cost of medical or dental care?",
    "How often do you feel that you are missing out on travel opportunities?",
    "How much do you worry about being able to afford a car one day?",
    "How often do you feel that your pocket money doesn't last the week?",
    "How much do you worry about the cost of prom or school dances?",
    "How often do you feel that you have to choose between food and school supplies?",
    "How much do you worry about the cost of your phone plan?",
    "How often do you feel that you can't afford the 'right' brand of shoes?",
    "How much do you worry about your family's ability to pay rent or mortgage?",
    "How often do you feel that you are falling behind on your savings?",
    "How much do you worry about the cost of extra tutoring or classes?",
    "How often do you feel that you have to work too many hours at a job?",
    "How much do you worry about the cost of printing or project materials?",
    "How often do you feel that your financial situation limits your career choices?",
    "How much do you worry about the cost of health insurance?",
    "How often do you feel that you have to borrow money from friends?",
    "How much do you worry about the cost of holiday gifts?",
    "How often do you feel that your lifestyle is unsustainable financially?",
    "How much do you worry about the cost of internet and electricity?",
    "How often do you feel that you will never be financially independent?"
],
   family: [
    "How much do your family's expectations stress you out?",
    "How often do you feel pressure at home?",
    "How well do you feel your family understands your school stress?",
    "How often do family arguments affect your mood?",
    "How much do you feel your parents compare you to siblings?",
    "How often do you feel unable to meet family expectations?",
    "How supported do you feel by your family during difficult times?",
    "How much do family responsibilities interfere with your studies?",
    "How often do you feel misunderstood by your family?",
    "How much does family conflict affect your concentration?",
    "How often do you feel you have to play the role of 'peacemaker' at home?",
    "How much do you worry about your parents' health or well-being?",
    "How often do you feel that your parents are too controlling?",
    "How much do you feel that your family respects your privacy?",
    "How often do you feel that you can't talk to your parents about your feelings?",
    "How much do you worry about living up to a sibling's success?",
    "How often do you feel that your home environment is too loud for studying?",
    "How much do you feel that your family values grades over your mental health?",
    "How often do you feel that you are carrying your family's hopes and dreams?",
    "How much do you worry about your parents' relationship with each other?",
    "How often do you feel that your family ignores your personal boundaries?",
    "How much do you feel that you have to hide parts of your life from your family?",
    "How often do you feel that your parents don't trust you?",
    "How much do you worry about family gatherings or holidays?",
    "How often do you feel that your family is over-involved in your social life?",
    "How much do you feel that your culture or traditions conflict with school?",
    "How often do you feel that your family doesn't spend enough time together?",
    "How much do you worry about your grandparents' health?",
    "How often do you feel that you are the 'black sheep' of the family?",
    "How much do you feel that your parents are living their lives through you?",
    "How often do you feel that your family is too critical of your friends?",
    "How much do you worry about your family’s reputation in the community?",
    "How often do you feel that you have to take care of your younger siblings?",
    "How much do you feel that your family is disappointed in your choices?",
    "How often do you feel that your home is a place of stress rather than rest?",
    "How much do you worry about your family moving or changing houses?",
    "How often do you feel that your parents' discipline is too harsh?",
    "How much do you feel that your family doesn't listen to your opinion?",
    "How often do you feel that your family is too focused on appearances?",
    "How much do you worry about how your family will react to your mistakes?",
    "How often do you feel that you are being forced into a specific career by family?",
    "How much do you feel that your family ignores your achievements?",
    "How often do you feel that your family is too competitive with each other?",
    "How much do you worry about family secrets or 'taboo' topics?",
    "How often do you feel that you lack a strong role model in your family?",
    "How much do you feel that your parents compare you to their friends' kids?",
    "How often do you feel that you are not given enough independence at home?",
    "How much do you worry about your parents getting older?",
    "How often do you feel that your family doesn't celebrate your uniqueness?",
    "How much do you feel that you will never be able to satisfy your family?"
]
};
